name: Manual upstream sync

on:
  workflow_dispatch:

jobs:
  sync:
    name: Sync fork
    runs-on: ubuntu-latest

    steps:
      - name: Sync
        run: gh repo sync ${{ vars.MY_WINGET_PKGS_REPO }}
        env:
          GH_TOKEN: ${{ secrets.KOMAC_TOKEN }}
