name: Release WinGet package

on:
  workflow_dispatch:
    inputs:
      identifier:
        description: 'The package identifier'
        required: true
      repo:
        description: "The repository's path (owner/name)"
        required: true
      url:
        description: 'Release URL'
        required: true

jobs:
  update:
    name: Release package
    runs-on: ubuntu-latest

    steps:
    - name: Release package
      uses: michidk/winget-updater@v1
      with:
        komac-token: ${{ secrets.KOMAC_TOKEN }}
        identifier: ${{ inputs.identifier }}
        repo: ${{ inputs.repo }}
        url: ${{ inputs.url }}

  cleanup:
    name: Clean up lingering branches
    runs-on: ubuntu-latest

    steps:
    - name: Clean up
      uses: michidk/run-komac@v2
      with:
        args: 'cleanup --only-merged --token=${{ secrets.KOMAC_TOKEN }}'